# Site settings
title: Oracle
email: askcoye@gmial.com
baseurl: "/Cloud" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site

# Sidebar settings
description: Hello World !

# Social icons
#facebook: username
#linkedin: username
github: askCoye
#deviantart: username
#codepen: username

footer: © Taken theme

# Build settings
markdown: kramdown

timezone: TIMEZONE
